test: set tolerance so test doesn't error
Set the tolerance low enough so that the test doesn't fail anymore with
error message

```
ValueError: list.remove(x): x not in list
```